<a href="https://colab.research.google.com/github/BMugo84/pytorch_in_25_hours/blob/main/pytorch00Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. Pytorch fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


## intro to tensors

### creating tensors

We create tensors by using `torch.tensor()`

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# scalar dimensions
scalar.ndim

0

In [ ]:
# scalar shape
scalar.shape

torch.Size([])

In [ ]:
# get scalar item
scalar.item()

7

In [ ]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# vector dimensions
vector.ndim

1

In [ ]:
# vector shape
vector.shape

torch.Size([2])

In [ ]:
# matrix
MATRIX = torch.tensor([
    [7,8],
    [9, 10]
])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# matrix dimensions . dimensions are counted by rows
MATRIX.ndim

2

In [ ]:
# matrix shape
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# tensor
TENSOR = torch.tensor([[
    [1,2,3],
    [2,4,6],
    [3,6,9]
]])
TENSOR

tensor([[[1, 2, 3],
         [2, 4, 6],
         [3, 6, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# the first dim matches with the first encapsulation bracket ie one tensor
TENSOR[0]

tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])

In [ ]:
# the second dim matches with the number of rows
print(TENSOR[0][0])
print(TENSOR[0][1])
print(TENSOR[0][2])

tensor([1, 2, 3])
tensor([2, 4, 6])
tensor([3, 6, 9])


In [ ]:
# the third dim matches with the columns
print(TENSOR[0][0][0])
print(TENSOR[0][0][1])
print(TENSOR[0][0][2])

tensor(1)
tensor(2)
tensor(3)


In [ ]:
# prompt: a 4x4 tensor example

tensor_1 = torch.tensor([[
    [7,8,9,10],
    [11,12,13,14],
    [15,16,17,18],
    [19,20,21,22]
]])
print("tensor visualization\n", tensor_1)
print("tensor dimensions", tensor_1.ndim)
print("tensor shape", tensor_1.shape)


tensor visualization
 tensor([[[ 7,  8,  9, 10],
         [11, 12, 13, 14],
         [15, 16, 17, 18],
         [19, 20, 21, 22]]])
tensor dimensions 3
tensor shape torch.Size([1, 4, 4])


### random tensors

why random tensors?

Random tensors are important because of the way neural netwroks work.
neural networks learn by starting off with tensors full of random numbers then adjust those random numbers to better represent data

`start with random numbers -> look at data -> update random numbers -> look at data`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# create random tensor
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.9915, 0.1794, 0.6501, 0.0695],
         [0.7835, 0.4934, 0.6938, 0.3065],
         [0.9680, 0.9333, 0.0447, 0.9577]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# create a random tensor similar to an image tensor ie (height, width, colorscheme)
random_image_tensor = torch.rand(224,224,3)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### zeros and ones

In [ ]:
# create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all zeros
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### range of tensors

In [ ]:
# create a tensor of range 1-10
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# create a tensor of range 1-10
one_to_ten = torch.arange(start=1, end=11, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])



### Tensor Data Types

Tensor data types are among the three major errors you may encounter when running PyTorch, namely:

1. Incorrect shape
2. Incorrect data type
3. Incorrect device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# convert from 32bit to 16bit . useful for changing datatype incase of datatype error
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# multiplying two diff datatypes
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])



### Accessing Tensor Information with PyTorch

To address issues with tensors:

1. Check for correct data type: Use `torch.dtype` attribute.
2. Verify correct shape: Utilize `torch.size()` or `torch.shape` attribute.
3. Confirm correct device: Employ `torch.device` attribute.

In [ ]:
# create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7802, 0.6532, 0.4154, 0.2684],
        [0.5562, 0.2541, 0.4015, 0.3637],
        [0.4584, 0.7014, 0.6103, 0.3177]])

In [ ]:
print("Data type:", some_tensor.dtype)
print("Shape:", some_tensor.shape)
print("Device:", some_tensor.device)


Data type: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Manipulating tensors

Tensor operation include:
* addition
* subtraction
* multiplication(elemental matrix)
* multiplication(dot product matrix)
* division

In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
#add
tensor+10

tensor([11, 12, 13])

In [ ]:
# subtraction
tensor-10

tensor([-9, -8, -7])

In [ ]:
# multiplication
tensor*10


tensor([10, 20, 30])

#### matrix multiplication
two ways of multiplying matrices
elementwise
matrix multiplication(dot product)


In [ ]:
# elementwise multiplication
tensor*tensor

tensor([1, 4, 9])

In [ ]:
# matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 634 µs, sys: 941 µs, total: 1.57 ms
Wall time: 11 ms


tensor(14)

In [ ]:
# matrix multiplication in a for loop
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i]*tensor[i]

print(value)

tensor(14)
CPU times: user 1.95 ms, sys: 0 ns, total: 1.95 ms
Wall time: 2.04 ms




### Two Main Rules for Matrix Multiplication

Matrix multiplication has two fundamental rules:

1. **Inner Dimensions Must Match:** The number of columns in the first matrix must equal the number of rows in the second matrix for multiplication to be possible.
   - For example, multiplying a (3,2) matrix by another (3,2) matrix won't work because the inner dimensions (columns of the first matrix and rows of the second matrix) don't match.
   - However, multiplying a (3,2) matrix by a (2,3) matrix will work because the inner dimensions match.
   - Similarly, multiplying a (2,3) matrix by a (3,2) matrix will also work.
2. **Resulting Matrix Shape:** The resulting matrix will have the shape of the outer dimensions.
    - (2,3) matrix @ (3,2) matrix will result in a (2,2) matrix.
    - (3,2) matrix @ (2,3) matrix will result in a (3,3) matrix.


In [ ]:


# Define three matrices
matrix1 = torch.randn(3, 2)  # (3, 2) matrix
matrix2 = torch.randn(2, 3)  # (2, 3) matrix




In [ ]:
torch.matmul(matrix1,matrix1)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.matmul(matrix1, matrix2)

tensor([[-3.0237,  1.8733,  0.4848],
        [ 1.4116, -0.1419, -0.8780],
        [ 1.3813, -0.4766, -0.5587]])

In [ ]:
torch.matmul(matrix2,matrix1)

tensor([[-2.4652,  2.1840],
        [ 2.1240, -1.2591]])

### shape errors

In [ ]:
# shapes for matrix multiplication
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.mm(tensor_a, tensor_b)  # mm == matmul==matrix multiplication

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix tensor shape issues, we can manipulate the shape of our tensors using transpose ie shifting matrix rows to columns and columns to rows

In [ ]:
tensor_b

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [ ]:
tensor_b_transposed = tensor_b.T
tensor_b_transposed, tensor_b_transposed.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
result = torch.matmul(tensor_a, tensor_b_transposed)
result, result.shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]),
 torch.Size([3, 3]))

## finding the min max,sum, mean, etc(tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(start=0, end = 100, step = 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# find the min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
# find max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
# The mean() function in PyTorch requires the input tensor to have a
# floating-point data type (like float32 or float64) to perform the calculation.
# x.mean()

In [ ]:
# find mean of x
x_float = x.type(torch.float32)
x_float.mean()

tensor(45.)

In [ ]:
# find the sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

In [ ]:
# find the position of the minimum value
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
# find the position of the max value
x.argmax(), torch.argmax(x)

(tensor(9), tensor(9))

## reshaping, stacking squeezing and unsqueezing tensors

- **Reshaping Tensors:** Reshaping allows altering the shape of a tensor while preserving its underlying data.
- **Stacking Tensors:** Stacking combines tensors along a new dimension to create higher-dimensional tensors.
- **Squeezing Tensors:** Squeezing removes dimensions with a size of 1 from a tensor.
- **Unsqueezing Tensors:** Unsqueezing adds dimensions with a size of 1 to a tensor.
- **View:** View allows reshaping a tensor without changing its data, useful for rearranging dimensions or flattening.
- **Permute:** Permute reorders the dimensions of a tensor, enabling arbitrary rearrangement of axes.

In [ ]:
# new tensor
x = torch.arange(start=1., end=10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimension
# NB: reshape has to be compatible with the original size
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# change view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# manipulate z
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stacking
x_stacked_v = torch.stack([x,x,x,x], dim=1)
x_stacked_v

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked_h = torch.stack([x,x,x,x], dim=0)
x_stacked_h

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# squeeze tensor ie remove single dimensions from a target tensor
x_squeezed = x_reshaped.squeeze()
print("Tensor: ", x_reshaped)
print("tensor shape:", x_reshaped.shape)
print("Tensor: ", x_squeezed)
print("tensor shape:", x_squeezed.shape)

Tensor:  tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor shape: torch.Size([1, 9])
Tensor:  tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor shape: torch.Size([9])


In [ ]:
# unsqueeze the squeezed tensor ie add dimensions to your tensor
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# permute rearranged the dims of a tensor in a specified order. used mostly with
# images
x_image = torch.rand(size=(224,224,3))
x_image_permuted = x_image.permute(2,0,1)
print("image",x_image.shape)
print("image permuted",x_image_permuted.shape)


image torch.Size([224, 224, 3])
image permuted torch.Size([3, 224, 224])


## tensor indexing

In [ ]:
# new tensor
x = torch.randint(low=0, high=10, size=(3, 3, 3))
x


tensor([[[9, 0, 4],
         [5, 2, 0],
         [3, 7, 5]],

        [[0, 8, 0],
         [8, 6, 8],
         [4, 3, 6]],

        [[1, 1, 2],
         [8, 5, 5],
         [5, 0, 1]]])

In [ ]:
# index on dim=0
x[0], x[1], x[2]

(tensor([[9, 0, 4],
         [5, 2, 0],
         [3, 7, 5]]),
 tensor([[0, 8, 0],
         [8, 6, 8],
         [4, 3, 6]]),
 tensor([[1, 1, 2],
         [8, 5, 5],
         [5, 0, 1]]))

In [ ]:
# index on dim=1
x[0][0]

tensor([9, 0, 4])

In [ ]:
# index on dim=2
x[0][0][0]

tensor(9)

## Pytorch tensors and Numpy

* numpy data to tensor -> `torch.from_numpy(ndarray)`
* tensor to numpy data -> `torch.Tensor.numpy()`

In [ ]:
# Numpy to tensor
array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# default numpy datatype
array.dtype

dtype('float64')

In [ ]:
# tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## reproducabilty

### How does a neural network learn?:

`start with random numbers -> tensor operations -> update random numbers to make them better represent data ->tensor operations ....`

to reduce randomness in neural networks and pytorch, we use **random seed**

random seed flavour the randomness

In [ ]:
# create two random tensors
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3, 4)

print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.4002, 0.8435, 0.5192, 0.5413],
        [0.4203, 0.8209, 0.1897, 0.7791],
        [0.1678, 0.0080, 0.1511, 0.5913]])
tensor([[0.3467, 0.5342, 0.4883, 0.3194],
        [0.3978, 0.3563, 0.6594, 0.8405],
        [0.9015, 0.3794, 0.8066, 0.7772]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# making random but reproducable tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)


print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## running tensors and pytorch objects on GPUs and making the computations faster

In [ ]:
# check for gpu access
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code

device = "cuda" if torch.cuda.is_available() else "cpu"
device


'cuda'

In [ ]:
# number of devices
torch.cuda.device_count()

1

## putting tensors on the GPU(for faster computation)

In [ ]:
# create a tensor
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# move tensor to GPU
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


## moving tensors to cpu

In [ ]:
# numpy cant run on gpu
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_to_cpu

array([1, 2, 3])